[package]
name = "gis_random_groups"
version = "0.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1"
rand = "0"
structopt = "0"
colored = "2"